# This file is not part of official PostgreSQL chart
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "postgresql.name" . }}-db-init
data:
  init-provisioner-db.sql: |
    CREATE DATABASE {{ .Values.global.database.embedded.provisioner.name }};
  init-broker-db.sql: |
    CREATE DATABASE {{ .Values.global.database.embedded.broker.name }};
