apiVersion: hydra.ory.sh/v1alpha1
kind: OAuth2Client
metadata:
  name: {{ include "fullname" . }}
spec:
  grantTypes:
    - "client_credentials"
  scope: "broker:write"
  secretName: {{ include "fullname" . }}-oauth