apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fullname" . }}
  labels:
{{ include "kyma-env-broker.labels" . | indent 4 }}
data:
  additionalRuntimeComponents.yaml: |-
    components:
{{- with .Values.additionalRuntimeComponents }}
{{ tpl . $ | indent 6 }}
{{- end }}