apiVersion: v1
kind: ConfigMap
metadata:
  name: compass-overrides
  namespace: compass-installer
  labels:
    installer: overrides
    component: compass
    kyma-project.io/installation: ""
data:
  global.provisioning.enabled: true
  provisioner.gardener.kubeconfig=$(base64 < "${GARDENER_KUBECONFIG_PATH}")
  provisioner.gardener.project=$GARDENER_PROJECT_NAME
